### ISSUE TITLE
Terrain fails to load whether or not allowed blocks is specified

### ISSUE THREAD

**Issue by JordanPlayz158** [WeiiswurstDev/PlaceStom#2]
I noticed the error in initialization of the PlaceBlocks object and checked to see and noticed the log error on line 61 ("Unable to load allowed blocks. Will default to list of concrete blocks, creating a map will not work") and as I didn't specify an allowed blocks list, I tried to and it resulted in the same error (I tried `-Dplacestom.blocks.allowed-blocks=grass_block,dirt_block`), also it spams this
```
Exception in thread "ForkJoinPool.commonPool-worker-1" java.lang.NoClassDefFoundError: Could not initialize class dev.weiiswurst.placestom.world.PlaceBlocks
        at dev.weiiswurst.placestom.world.PlaceLoader.generateChunkData(PlaceLoader.java:32)
        at net.minestom.server.instance.batch.ChunkGenerationBatch.lambda$generate$0(ChunkGenerationBatch.java:34)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
in console which makes the log error unintuitive if it even gets to this point (not sure if it's erroring before or after that log or if the error isn't gracefully handled) also this is not documented or mentioned anywhere in the readme, also there should be a default fallback that allows terrain to generate normally without spam erroring out on player join (Might make a pr to fix the 2 issues

**Comment by ArvedEh** [comment]
This sounds very similar to #1, because both issues come from the server not properly loading the properties from the file. I have not tested the command line args you use, in my usecases I would just edit the file. 

In any case, please read my comment on #1 and I hope we can fix this :)

**Comment by JordanPlayz158** [comment]
I'm so sorry for wasting your time, I was running it through pterodactyl and didn't make an egg for minestom and the minecraft eggs auto make the server.properties at the start of the container everytime so that was impossible for me to test but it seems to be working after making an egg for it and not forcing a server.properties to be automade.

**Comment by JordanPlayz158** [comment]
Refer to #1 if you wish to have an egg that "fixes" the issue
